project:
  type: default
  output-dir: _output

execute:
  freeze: auto
  cache: true

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    embed-resources: true
    theme: cosmo
    fig-width: 9
    fig-height: 5

jupyter: python3
