{
 "title": "Контейнеры",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Память контейнеров, сумма",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.+\"})"
    }
   ]
  },
  {
   "title": "Макс. занятость файловой системы",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_fs_usage_bytes / container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Контейнеров",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/docker/.+\"})"
    }
   ]
  },
  {
   "title": "Память по контейнерам",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.+\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU по контейнерам, ядер",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(id)(rate(container_cpu_usage_seconds_total{id=~\"/docker/.+\"}[5m]))",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}